MyTask.UI/Models/TaskReportViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MyTask.UI.Models
{
    public class TaskReportViewModel
    {
        public Guid Id { get; set; }
        public Guid TaskId { get; set; }
        public Guid UserId { get; set; }

        [DataType(DataType.Date)]
        public DateTime DateOfReport { get; set; }

        [DataType(DataType.Date)]
        public DateTime CreatedDate { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime EditedDate { get; set; }
        public string Description { get; set; }

        [DataType(DataType.Time)]
        public TimeSpan Effort { get; set; }
    }
}

MyTask.UI/Controllers/TaskReportController.cs
using AutoMapper;
using MyTask.Domain.Models;
using MyTask.Domain.Repositories;
using MyTask.Domain.Services;
using MyTask.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace MyTask.UI.Controllers
{
    public class TaskReportController : Controller
    {
        private readonly ITaskReportService _taskReportService;
        public TaskReportController(ITaskReportService taskReportService)
        {
            _taskReportService = taskReportService;
        }

        public PartialViewResult Index(Guid userId, Guid taskId)
        {
            var taskreportsList = _taskReportService.ShowAllReportsForUser(userId, taskId);

            var viewModel = Mapper.Map<IEnumerable<TaskReportViewModel>>(taskreportsList);

            return PartialView(viewModel);
        }

        public ActionResult Description(Guid reportId)
        {           
            var report = _taskReportService.ShowTaskReport(reportId);
            var viewModel = Mapper.Map<TaskReportViewModel>(report);

            return View(viewModel);
        }

        public ActionResult Create(Guid taskId)
        {
            var report = new TaskReportViewModel();
            report.TaskId = taskId;
            report.UserId = new Guid(User.Identity.GetUserId());
            return View(report);
        }
        [HttpPost]
        public ActionResult Create(TaskReportViewModel taskreport)
        {
            var newreport = Mapper.Map<TaskReport>(taskreport);
            _taskReportService.CreateTaskReport(newreport);
            return RedirectToAction("Description", "Tasks" , new { id = newreport.TaskId });
        }
        public ActionResult Edit(Guid reportId)
        {
            var report = _taskReportService.ShowTaskReport(reportId);
            var viewModel = Mapper.Map<TaskReportViewModel>(report);
            return View(viewModel);
        }
        [HttpPost]
        public ActionResult Edit(TaskReportViewModel taskreport)
        { 
            var domainreport = Mapper.Map<TaskReport>(taskreport);
            _taskReportService.EditTaskReport(domainreport);
            return RedirectToAction("Description", new { reportId = domainreport.Id });
        }

    }
}

MyTask.UI/Views/TaskReport/Create.cshtml
@using Microsoft.AspNet.Identity
@using MyTask.UI.Infrastructure
@model MyTask.UI.Models.TaskReportViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       @Html.HiddenFor(model => model.TaskId)
      @Html.HiddenFor(model => model.UserId)

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfReport, new { @class = "col-xs-2 control-label" })
            <div class="datepicker">
                @Html.DatepickerFor(model => model.DateOfReport, new { @class = "form-control" })
            </div>
        </div>

       <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Effort, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Effort, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Effort, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Description of Task", "Tasks", new { id = Model.TaskId })
</div>

MyTask.UI/Views/TaskReport/Description.cshtml
@model MyTask.UI.Models.TaskReportViewModel

@{
    ViewBag.Title = "Description";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Description</h2>

<div>
   
    <hr />
    <dl class="dl-horizontal">
     
        <dt>
            @Html.DisplayNameFor(model => model.DateOfReport)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfReport)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EditedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EditedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Effort)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Effort)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { reportId = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MyTask.UI/Views/TaskReport/Edit.cshtml
@using MyTask.UI.Infrastructure
@model MyTask.UI.Models.TaskReportViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.TaskId)
        @Html.HiddenFor(model => model.UserId)
        @Html.HiddenFor(model => model.CreatedDate)
        @Html.HiddenFor(model => model.EditedDate)
     
        <div class="form-group">
            @Html.LabelFor(model => model.DateOfReport, new { @class = "col-xs-2 control-label" })
            <div class="datepicker">
                @Html.DatepickerFor(model => model.DateOfReport, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Effort, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Effort, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Effort, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-xs-offset-2 col-xs-10">
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MyTask.UI/Views/TaskReport/Index.cshtml
@model IEnumerable<MyTask.UI.Models.TaskReportViewModel>

<h2>Your Reports</h2>

<table class="table">
    <thead>
        <tr>
            <th>Date of Report</th>
            <th>Created Date</th>
            <th>Edited Date</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var report in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(t => report.DateOfReport)
                </td>
                <td>
                    @Html.DisplayFor(t => report.CreatedDate)
                </td>
                <td>
                    @Html.DisplayFor(t => report.EditedDate)
                </td>
                <th>
                    @Html.ActionLink("Description", "Description", "TaskReport", new { reportId = report.Id }, new { @class = "btn btn-default btn-sm" })
                </th>
                <th>
                    @Html.ActionLink("Edit", "Edit", "TaskReport", new { reportId = report.Id }, new { @class = "btn btn-default btn-sm" })
                </th>
            </tr>
           
        }
    </tbody>
   
   
</table>

MyTask.UI/Views/TaskReport/Report.cshtml
@model MyTask.UI.Models.TaskReportViewModel
@{
    ViewBag.Title = "Report " ;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Report</h2>

        <div class="row">
            <div class="col-xs-8 col-xs-offset-2">
                <div class="top-buffer">
                    <strong class="text-uppercase">@Html.DisplayNameFor(pr => pr.DateOfReport):</strong> @Html.DisplayFor(pr => pr.DateOfReport)
                </div>
                <div class="top-buffer">
                    <strong class="text-uppercase">@Html.DisplayNameFor(pr => pr.CreatedDate):</strong> @Html.DisplayFor(pr => pr.CreatedDate)
                </div>
                <div class="top-buffer">
                    <strong class="text-uppercase">@Html.DisplayNameFor(pr => pr.EditedDate):</strong> @Html.DisplayFor(pr => pr.EditedDate)
                </div>
                <div class="top-buffer">
                    <strong class="text-uppercase">@Html.DisplayNameFor(pr => pr.Description):</strong><br />@Html.DisplayFor(pr => pr.Description)
                </div>
                <div class="top-buffer">
                    <strong class="text-uppercase">@Html.DisplayNameFor(pr => pr.Effort):</strong><br />@Html.DisplayFor(pr => pr.Effort)
                </div>
                

            </div>
        </div>
   