MyTask.UI/Controllers/ProjectController.cs
using AutoMapper;
using MyTask.Domain.Repositories;
using MyTask.Domain.Services;
using MyTask.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyTask.UI.Controllers
{
    public class ProjectController : Controller
    {
        private readonly IProjectService _projectService;
        public ProjectController(IProjectService projectService)
        {
            _projectService = projectService;
        }
        public ActionResult Index()
        {
            var projectList = _projectService.ShowAvaliableProjects();

            var viewModel = Mapper.Map<IEnumerable<ProjectViewModel>>(projectList);

            return View(viewModel);
        }
        public ActionResult Description(Guid id)
        {
            var project = _projectService.ShowProjectDecription(id);
            var viewModel = Mapper.Map<ProjectViewModel>(project);

            return View(viewModel);
        }
    }
}

MyTask.UI/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@{
    var claimsIdentity = User.Identity as ClaimsIdentity;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap-datepicker.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MyTask", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Projects", "Index", "Project")</li>
                        @if (User != null && User.Identity.IsAuthenticated && claimsIdentity.HasClaim(ClaimTypes.Role, "Admin"))
                        {
                    <li>@Html.ActionLink("Administration", "Index", "Admin")</li>
                        }
                </ul>
                @Html.Action("Login", "Login")
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderSection("SubHeader",false)
        <div class="container-fluid top-buffer">
            @RenderBody()
            </div>
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.min.js"></script>
</body>
</html>