MyTask.UI/Models/ProjectViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyTask.UI.Models
{
    public class ProjectViewModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public TasksViewModel Task { get; set; }

    }
}

MyTask.UI/Controllers/ProjectController.cs
using AutoMapper;
using MyTask.Domain.Repositories;
using MyTask.Domain.Services;
using MyTask.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyTask.UI.Controllers
{
    public class ProjectController : Controller
    {
        private readonly IProjectService _projectService;
        public ProjectController(IProjectService projectService)
        {
            _projectService = projectService;
        }
        public ActionResult Index()
        {
            var projectList = _projectService.ShowAvaliableProjects();

            var viewModel = Mapper.Map<IEnumerable<ProjectViewModel>>(projectList);

            return View(viewModel);
        }
        public ActionResult Description(Guid id)
        {
            var project = _projectService.ShowProjectDecription(id);
            var viewModel = Mapper.Map<ProjectViewModel>(project);

            return View(viewModel);
        }
    }
}

MyTask.UI/Controllers/TasksController.cs
using AutoMapper;
using MyTask.Domain.Models;
using MyTask.Domain.Repositories;
using MyTask.Domain.Services;
using MyTask.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyTask.UI.Controllers
{
    public class TasksController : Controller
    {
        // GET: Tasks
        private readonly ITasksService _tasksService;
        public TasksController(ITasksService tasksService)
        {
            _tasksService = tasksService;
        }
        public PartialViewResult Index(Guid id)
        {
            var tasksList = _tasksService.ShowTasks(id);

            var viewModel = Mapper.Map<IEnumerable<TasksViewModel>>(tasksList);

            return PartialView(viewModel);
        }
        public ActionResult Description(Guid id)
        {
            var tasks = _tasksService.ShowTaskDecription(id); 
            var viewModel = Mapper.Map<TasksViewModel>(tasks);

            return View(viewModel);
        }

      
    }
}

MyTask.UI/Views/Project/Description.cshtml
@model MyTask.UI.Models.ProjectViewModel
@{
    ViewBag.Title = "Description - " + Model.Name;
   
}

<h2>Description</h2>

<div class="panel panel-default">
       <div class="panel-heading">
            <h3>@Html.DisplayFor(pr => pr.Name)</h3>
        
    </div>
    <div class="panel-body">

        <div class="row">
            <div class="col-xs-8 col-xs-offset-2">
                <div class="top-buffer">
                    <strong class="text-uppercase">@Html.DisplayNameFor(pr => pr.StartDate):</strong> @Html.DisplayFor(pr => pr.StartDate)
                </div>
                <div class="top-buffer">
                    <strong class="text-uppercase">@Html.DisplayNameFor(pr => pr.EndDate):</strong> @Html.DisplayFor(pr => pr.EndDate)
                </div>
                <div class="top-buffer">
                    <strong class="text-uppercase">@Html.DisplayNameFor(pr => pr.Description):</strong><br />@Html.DisplayFor(pr => pr.Description)
                </div>

            </div>
        </div>
    </div>
        @Html.Action("Index", "Tasks")
        
   
    
</div>

MyTask.UI/Views/Project/Index.cshtml
@model IEnumerable<MyTask.UI.Models.ProjectViewModel>

@{
    ViewBag.Title = "Project";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>You may take part in follow projects</h2>

<table class="table table-responsive table-hover table-condensed">
    <thead>
        <tr>
            <th>Name</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var proj in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(p => proj.Name)
                </td>
                <td>
                    @Html.DisplayFor(p => proj.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(p => proj.EndDate)
                </td>
                <th>
                    @Html.ActionLink("Description", "Description", "Project", new { id = proj.Id }, new { @class = "btn btn-default btn-sm" })
                </th>
            </tr>
        }
    </tbody>
</table>